"""
Tier 3 — Fulfillment Engine
Bridges the gap between recommendation and action.
Generates recipes, grocery lists, and mock restaurant order data.
"""

import json
import logging
import os
import random
import time
import urllib.parse
from abc import ABC, abstractmethod

import httpx

from tier_1.contracts.schemas import Restaurant
from tier_1.contracts.session_store import get_redis

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
log = logging.getLogger(__name__)

# ── Recipe Database ─────────────────────────────────────────────────────────
# Curated recipes for the dish catalog. In production, this would be
# generated by the LLM or fetched from a recipe API.

RECIPES = {
    "Dal Tadka": {
        "prep_time": "10 min",
        "cook_time": "25 min",
        "servings": 2,
        "difficulty": "Easy",
        "steps": [
            "Wash and soak 1 cup of lentils for 15 minutes.",
            "Pressure cook lentils with turmeric, salt, and 2.5 cups water for 3 whistles.",
            "Heat ghee in a pan. Add cumin seeds and let them splutter.",
            "Add finely chopped onion, garlic, and ginger. Sauté until golden.",
            "Add chopped tomatoes and cook until soft.",
            "Add chili powder and coriander. Mix well.",
            "Pour the tadka over the cooked dal. Stir and simmer for 5 minutes.",
            "Garnish with fresh coriander and serve hot with rice or naan.",
        ],
        "grocery_list": [
            {"item": "Red Lentils (Masoor Dal)", "qty": "1 cup", "est_cost": 60},
            {"item": "Onion", "qty": "1 medium", "est_cost": 15},
            {"item": "Tomato", "qty": "2 medium", "est_cost": 20},
            {"item": "Garlic cloves", "qty": "4", "est_cost": 10},
            {"item": "Ginger", "qty": "1 inch", "est_cost": 10},
            {"item": "Ghee", "qty": "2 tbsp", "est_cost": 30},
            {"item": "Cumin seeds", "qty": "1 tsp", "est_cost": 5},
            {"item": "Turmeric", "qty": "½ tsp", "est_cost": 5},
            {"item": "Red chili powder", "qty": "1 tsp", "est_cost": 5},
            {"item": "Fresh coriander", "qty": "1 bunch", "est_cost": 10},
        ],
    },
    "Chicken Karahi": {
        "prep_time": "15 min",
        "cook_time": "35 min",
        "servings": 3,
        "difficulty": "Medium",
        "steps": [
            "Cut 500g chicken into medium pieces. Wash and pat dry.",
            "Heat oil in a karahi (wok). Add chopped onions and fry until light golden.",
            "Add garlic-ginger paste and sauté for 2 minutes.",
            "Add chicken pieces. Cook on high heat for 5 minutes, stirring frequently.",
            "Add chopped tomatoes, salt, and red chili. Cover and cook for 15 minutes.",
            "Add sliced capsicum and garam masala. Cook uncovered for 10 minutes.",
            "Add green chilies and fresh coriander. Toss well.",
            "Serve hot in the karahi with naan.",
        ],
        "grocery_list": [
            {"item": "Chicken (whole cut)", "qty": "500g", "est_cost": 250},
            {"item": "Tomato", "qty": "4 medium", "est_cost": 40},
            {"item": "Onion", "qty": "2 medium", "est_cost": 30},
            {"item": "Capsicum", "qty": "1", "est_cost": 25},
            {"item": "Garlic-ginger paste", "qty": "2 tbsp", "est_cost": 15},
            {"item": "Green chilies", "qty": "4", "est_cost": 10},
            {"item": "Garam masala", "qty": "1 tsp", "est_cost": 10},
            {"item": "Cooking oil", "qty": "3 tbsp", "est_cost": 15},
            {"item": "Fresh coriander", "qty": "1 bunch", "est_cost": 10},
        ],
    },
    "Anda Curry": {
        "prep_time": "5 min",
        "cook_time": "20 min",
        "servings": 2,
        "difficulty": "Easy",
        "steps": [
            "Hard boil 4 eggs. Peel and make small slits with a knife.",
            "Heat oil in a pan. Add cumin seeds.",
            "Add chopped onion and cook until golden brown.",
            "Add garlic, ginger, and chopped tomatoes. Cook until tomatoes soften.",
            "Add turmeric, chili powder, and salt. Mix well.",
            "Add ½ cup water and let the gravy simmer for 5 minutes.",
            "Gently add the boiled eggs. Spoon gravy over them.",
            "Cover and cook for 5 more minutes. Garnish with coriander.",
        ],
        "grocery_list": [
            {"item": "Eggs", "qty": "4", "est_cost": 60},
            {"item": "Onion", "qty": "1 large", "est_cost": 15},
            {"item": "Tomato", "qty": "2 medium", "est_cost": 20},
            {"item": "Garlic", "qty": "3 cloves", "est_cost": 10},
            {"item": "Ginger", "qty": "1 inch", "est_cost": 10},
            {"item": "Cumin seeds", "qty": "1 tsp", "est_cost": 5},
            {"item": "Turmeric", "qty": "½ tsp", "est_cost": 5},
            {"item": "Red chili powder", "qty": "1 tsp", "est_cost": 5},
            {"item": "Cooking oil", "qty": "2 tbsp", "est_cost": 10},
        ],
    },
    "Palak Paneer": {
        "prep_time": "15 min",
        "cook_time": "25 min",
        "servings": 2,
        "difficulty": "Medium",
        "steps": [
            "Blanch 300g spinach in boiling water for 2 minutes. Transfer to ice water.",
            "Blend the spinach into a smooth puree.",
            "Cut 200g paneer into cubes. Lightly fry in oil until golden. Set aside.",
            "Heat oil, add cumin seeds, chopped onion, garlic, and ginger.",
            "Sauté until onion is soft. Add tomatoes and cook 5 minutes.",
            "Add the spinach puree, salt, garam masala, and a pinch of sugar.",
            "Simmer for 10 minutes. Add cream and paneer cubes.",
            "Cook for 5 more minutes. Serve hot with naan or roti.",
        ],
        "grocery_list": [
            {"item": "Fresh spinach", "qty": "300g", "est_cost": 40},
            {"item": "Paneer", "qty": "200g", "est_cost": 120},
            {"item": "Onion", "qty": "1 medium", "est_cost": 15},
            {"item": "Tomato", "qty": "1 medium", "est_cost": 10},
            {"item": "Cream", "qty": "2 tbsp", "est_cost": 25},
            {"item": "Garam masala", "qty": "1 tsp", "est_cost": 10},
            {"item": "Garlic-ginger", "qty": "1 tbsp", "est_cost": 10},
        ],
    },
}


# ── Generic recipe generator for dishes not in the curated database ──────────
def _generate_generic_recipe(dish_name: str, ingredients: list[str], price: float) -> dict:
    """Generates a plausible recipe structure from dish metadata."""
    return {
        "prep_time": "10 min",
        "cook_time": "30 min",
        "servings": 2,
        "difficulty": "Medium",
        "steps": [
            f"Prepare all ingredients for {dish_name}.",
            "Wash and chop vegetables. Prepare proteins if needed.",
            "Heat oil in a pan over medium heat.",
            "Add aromatics (onion, garlic, ginger) and sauté until fragrant.",
            "Add main ingredients and cook according to type.",
            "Season with spices, salt, and any sauces.",
            "Simmer until fully cooked and flavours meld together.",
            "Garnish and serve hot.",
        ],
        "grocery_list": [
            {"item": ing.title(), "qty": "as needed", "est_cost": max(5, int(price * 0.08))}
            for ing in ingredients[:8]  # Top 8 ingredients
        ],
    }


# ── Mock Restaurant Database ────────────────────────────────────────────────
MOCK_RESTAURANTS = [
    {
        "name": "Karachi Kitchen Express",
        "delivery_time": "25-35 min",
        "rating": 4.3,
        "delivery_fee": 50,
    },
    {"name": "Lahore Food Street", "delivery_time": "30-40 min", "rating": 4.5, "delivery_fee": 70},
    {"name": "Desi Dhaba Online", "delivery_time": "20-30 min", "rating": 4.1, "delivery_fee": 40},
    {
        "name": "Spice Route Delivery",
        "delivery_time": "35-45 min",
        "rating": 4.6,
        "delivery_fee": 80,
    },
]


def get_recipe(dish_name: str, ingredients: list[str] | None = None, price: float = 0) -> dict:
    """Returns a recipe for the dish. Uses curated DB first, generic fallback."""
    if dish_name in RECIPES:
        log.info("recipe found (curated): %s", dish_name)
        recipe = RECIPES[dish_name].copy()
        if "grocery_list" in recipe:
            recipe["grocery_list"] = [item.copy() for item in recipe["grocery_list"]]
        recipe["source"] = "curated"
    else:
        log.info("recipe generated (generic): %s", dish_name)
        if not ingredients:
            raise ValueError(f"Cannot generate recipe for '{dish_name}': empty ingredient list")
        recipe = _generate_generic_recipe(dish_name, ingredients, price)
        recipe["source"] = "generated"

    total = 0
    for item in recipe.get("grocery_list", []):
        cost = item.get("est_cost")
        if cost is None:
            item["est_cost"] = "price unavailable"
        else:
            try:
                total += float(cost)
            except (ValueError, TypeError):
                item["est_cost"] = "price unavailable"

    recipe["total_cost"] = total
    return recipe


class RestaurantProvider(ABC):
    @abstractmethod
    def find_nearby(self, dish_name: str) -> list[Restaurant]:
        """Find nearby restaurants that serve the specified dish."""
        pass


class MockRestaurantProvider(RestaurantProvider):
    def find_nearby(self, dish_name: str) -> list[Restaurant]:
        """Returns mock restaurant options that serve the dish."""
        random.seed(hash(dish_name) % 2**32)  # Deterministic per dish
        count = random.randint(2, len(MOCK_RESTAURANTS))
        selected = random.sample(MOCK_RESTAURANTS, count)

        restaurants = []
        for r in selected:
            # We copy to avoid modifying the global mock list directly
            r_copy = r.copy()
            r_copy["dish_available"] = dish_name
            restaurants.append(Restaurant(**r_copy))
        return restaurants


class OSMRestaurantProvider(RestaurantProvider):
    def find_nearby(self, dish_name: str) -> list[Restaurant]:
        """Queries Overpass API for restaurants in Islamabad."""
        redis_client = get_redis()
        cache_key = f"osm_cache:{dish_name}:islamabad"

        cached = redis_client.get(cache_key)
        if cached:
            log.info("OSMRestaurantProvider: cache hit for %s", dish_name)
            data = json.loads(cached)
            return [Restaurant(**r) for r in data]

        log.info("OSMRestaurantProvider: cache miss for %s", dish_name)

        # Rate limit: keep well under 2 requests/second
        last_req = redis_client.get("osm_last_request")
        if last_req:
            elapsed = time.time() - float(last_req)
            if elapsed < 0.6:
                time.sleep(0.6 - elapsed)

        redis_client.set("osm_last_request", time.time())

        # A simple Overpass query for restaurants in Islamabad.
        # Note: Overpass does not have delivery_time, rating, or delivery_fee.
        query = """
        [out:json][timeout:15];
        (
          node["amenity"~"restaurant|fast_food|cafe"](33.5,72.9,33.8,73.2);
        );
        out center 15;
        """

        url = "https://overpass-api.de/api/interpreter"
        try:
            resp = httpx.post(
                url,
                data={"data": query},
                headers={"User-Agent": "Mood4Food/1.0", "Accept": "*/*"},
                timeout=15.0,
            )
            resp.raise_for_status()
            elements = resp.json().get("elements", [])
        except Exception as e:
            log.error("Overpass API query failed: %s", e)
            elements = []

        # Shuffle to provide variety
        random.seed(hash(dish_name) % 2**32)
        random.shuffle(elements)

        restaurants = []
        for el in elements[:5]:
            tags = el.get("tags", {})
            name = tags.get("name", "Unknown Restaurant")
            if name == "Unknown Restaurant":
                continue

            lat = el.get("lat")
            lon = el.get("lon")
            # Build approximate address
            address_parts = [
                tags.get("addr:housenumber", ""),
                tags.get("addr:street", ""),
                tags.get("addr:suburb", ""),
                "Islamabad",
            ]
            address = ", ".join([p for p in address_parts if p])

            restaurants.append(
                Restaurant(
                    name=name,
                    delivery_time=None,  # Not available in OSM
                    rating=None,  # Not available in OSM
                    delivery_fee=None,  # Not available in OSM
                    dish_available=dish_name,
                    address=address,
                    lat=lat,
                    lon=lon,
                )
            )

        # Cache the result for 10 minutes (600 seconds)
        redis_client.set(cache_key, json.dumps([r.model_dump() for r in restaurants]), ex=600)

        return restaurants


def get_restaurant_provider() -> RestaurantProvider:
    provider = os.environ.get("RESTAURANT_PROVIDER", "mock").lower()
    if provider == "osm":
        return OSMRestaurantProvider()
    return MockRestaurantProvider()


def enrich_blueprint(blueprint: dict) -> dict:
    """Enriches a decision blueprint with fulfillment data (recipe + restaurants)."""
    dish_name = blueprint.get("winning_dish", {}).get("name", "")
    if not dish_name:
        return blueprint

    # Get ingredients from candidate scores if available
    ingredients = blueprint.get("winning_dish", {}).get("ingredients", [])
    price = blueprint.get("winning_dish", {}).get("price_pkr", 0)

    provider = get_restaurant_provider()

    blueprint["fulfillment"] = {
        "recipe": get_recipe(dish_name, ingredients, price),
        "restaurants": [r.model_dump() for r in provider.find_nearby(dish_name)],
    }

    log.info("blueprint enriched with fulfillment data for: %s", dish_name)
    return blueprint


def generate_foodpanda_link(restaurant_name: str, dish_name: str) -> str:
    """Generates a valid URL-encoded Foodpanda search link."""
    query = f"{restaurant_name} {dish_name}"
    encoded_query = urllib.parse.quote(query)
    return f"https://www.foodpanda.pk/search?q={encoded_query}"


def generate_whatsapp_link(phone: str, message: str) -> str:
    """Generates a valid URL-encoded WhatsApp deep link."""
    encoded_message = urllib.parse.quote(message)
    return f"https://wa.me/{phone}?text={encoded_message}"
