line-length = 100

[lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "W",  # pycodestyle warnings
]
ignore = []

[lint.per-file-ignores]
"test_suite.py" = ["E501"]
